### ISSUE TITLE
Question: Any plan to provide "yaml file" under "gen" directory?

### ISSUE THREAD

**Issue by miwamasa** [batterypass/BatteryPassDataModel#8]
From our experience with SAMM, yaml (OpenAPI spec) is very helpfile to understand the semantics of the data.
ex. put it into LLM for further analysis

Do you have any plan to add yaml file on the repository? that might

**Comment by miwamasa** [comment]
the "yaml file" can be easily obtained from *.ttl using sam-cli tool, so this question is not adequate
I close this by myself.

**Comment by nd-circulor** [comment]
Anyway, thank you for the hint.
